### ISSUE TITLE
After magisk installed - No wifi anymore.

### ISSUE THREAD

**Issue by henres** [LinuxDroidMaster/Lenovo-Legion-Y700-ROMs#2]
Hello, thanks for all your ressources.

I follow your tutorial https://github.com/LinuxDroidMaster/Lenovo-Legion-Y700-ROMs?tab=readme-ov-file#-how-to-flash-a-gsi-rom-

At one exception, I use the crDroid-10.1-arm64_bgN-Unofficial.img instead of crDroid-10.0-arm64_bgN-Unofficial.img.

After rebooting after the cgi install. Wifi was working fine.

Then I install magisk Magisk-v27.0.apk. And use your magiskPatchedBootB.img. After reboot. The wifi won't work anymore.

It tried to reinstall the crDroid image without magisk. Nothink worked ...

Can you help me get my wifi back ?

Thanks in advance

**Comment by LinuxDroidMaster** [comment]
Hi! Sorry for the delay, I think the error is related to the bootimg used and it depends if you were using ZUI 14 or 15 before rooting the device. There are more info about it in this post: https://xdaforums.com/t/gsi-rom-install-magisk-with-no-root-on-gsi-rom-dsu-method.4651428/

![image](https://github.com/LinuxDroidMaster/Lenovo-Legion-Y700-ROMs/assets/155466495/18ed2e4b-c6ef-44eb-bb3a-45f1989b81bf)

**Comment by LinuxDroidMaster** [comment]
I'm adding a new boot.img patched for people who has Wifi problems
